# Application Name
spring.application.name=facebook-media-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/facebookMediaDB

# Server Port
server.port=8080

# JWT Configuration
jwt.secret=8f9d3b2c1a7e4f5d9e3b2c1a7e4f5d9e3b2c1a7e4f5d9e3b2c1a7e4f5d9e3b2c1a # Use environment variables or secrets manager in production

# Logging Configuration
logging.level.org.springframework=INFO
