server:
  port: 8081
spring:
  application:
      name: AUTHSERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: iramabdullah@312
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: Hvq3HISlXwroXNFy0nEB2wUnb5swRI6mTZ0cnWnS2YC
  expiration: 86400000

