name: Hospital Management CI

on:
  push:
    branches:
      - feature/appointment-service

  pull_request:
    branches:
      - main

jobs:
  appointment-service-build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: AppointmentService/AppointmentService

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build AppointmentService
        run: mvn clean package

#Authservice-Build

  auth-service-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: authService/authService

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4

        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build AuthService
        run: mvn clean package

  doctor-service-build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DoctorService/DoctorService

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build DoctorService
        run: mvn clean package

  patient-service-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: PatientService/PatientService
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build PatientService
        run: mvn clean package

  eureka-server-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: EurekaServer/EurekaServer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build EurekaServer
        run: mvn clean package


